# Generated by Django 6.0.3 on 2026-09-02 13:46

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_heading', models.CharField(default='About Lex Chambers', max_length=200, verbose_name='Intro Heading')),
                ('intro_text', ckeditor.fields.RichTextField(help_text='The main introductory paragraph(s) on the about page.', verbose_name='Introduction Text')),
                ('intro_image', cloudinary.models.CloudinaryField(blank=True, help_text='Large image shown alongside the introduction. Recommended 800×600px.', max_length=255, verbose_name='Intro Image')),
                ('intro_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Intro Image Alt Text')),
                ('mission', ckeditor.fields.RichTextField(blank=True, verbose_name='Our Mission')),
                ('vision', ckeditor.fields.RichTextField(blank=True, verbose_name='Our Vision')),
                ('ethics', ckeditor.fields.RichTextField(blank=True, verbose_name='Our Ethics / Core Values')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Years of Experience')),
                ('cases_won', models.PositiveIntegerField(default=0, verbose_name='Cases Won')),
                ('clients_served', models.PositiveIntegerField(default=0, verbose_name='Clients Served')),
                ('team_size', models.PositiveSmallIntegerField(default=0, verbose_name='Team Size')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
