# Generated by Django 6.0.3 on 2026-09-03 09:33

from django.db import migrations, models


def update_placeholder_about(apps, schema_editor):
    AboutPage = apps.get_model('about', 'AboutPage')
    for obj in AboutPage.objects.all():
        if obj.intro_heading == 'About Lex Chambers':
            obj.intro_heading = 'About Subhash Mishra & Associates'
            obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_heading',
            field=models.CharField(default='About Subhash Mishra & Associates', max_length=200, verbose_name='Intro Heading'),
        ),
        migrations.RunPython(update_placeholder_about, noop_reverse),
    ]
