# Generated by Django 6.0.3 on 2026-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Optional.', max_length=30, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('is_read', models.BooleanField(default=False, help_text='Check this once you have addressed the enquiry.', verbose_name='Marked as Read')),
                ('telegram_sent', models.BooleanField(default=False, help_text='Set automatically. If False after a minute, the qcluster may not be running.', verbose_name='Telegram Notification Sent')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
