# Generated by Django 6.0.3 on 2026-09-02 13:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Recommended size: 1920×1080px. Will be used as full-bleed background.', max_length=255, verbose_name='Hero Slide Image')),
                ('image_alt', models.CharField(help_text='Describe the image for screen readers. Required for accessibility.', max_length=200, verbose_name='Image Alt Text')),
                ('kicker', models.CharField(blank=True, help_text='Small uppercase text above the heading (e.g. "PREMIER LAW FIRM").', max_length=100, verbose_name='Kicker / Eyebrow Text')),
                ('heading', models.CharField(max_length=200, verbose_name='Main Heading')),
                ('subheading', models.TextField(blank=True, help_text='Short description beneath the main heading.', verbose_name='Subheading / Description')),
                ('cta_text', models.CharField(blank=True, default='Schedule a Consultation', max_length=80, verbose_name='CTA Button Text')),
                ('cta_url', models.CharField(blank=True, default='/contact/', max_length=200, verbose_name='CTA Button URL')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide without deleting it.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='Lex Chambers', max_length=200, verbose_name='Firm Name')),
                ('firm_tagline', models.CharField(blank=True, default='Excellence in Legal Practice', max_length=300, verbose_name='Firm Tagline')),
                ('footer_about_text', models.TextField(blank=True, default='Lex Chambers is a premier law firm committed to providing exceptional legal services with integrity and dedication.', help_text='Short description shown in the footer beneath the logo.', verbose_name='Footer About Text')),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='Primary Phone')),
                ('phone_secondary', models.CharField(blank=True, help_text='Optional second phone number.', max_length=30, verbose_name='Secondary Phone')),
                ('email_primary', models.EmailField(blank=True, max_length=254, verbose_name='Primary Email')),
                ('office_hours', models.CharField(blank=True, default='Mon–Fri 09:00–20:00', max_length=100, verbose_name='Office Hours')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='PIN Code')),
                ('google_map_embed_url', models.TextField(blank=True, help_text='Paste the src URL from a Google Maps embed code. Go to Google Maps → Share → Embed a map → copy the src="..." value.', verbose_name='Google Map Embed URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Create a bot via @BotFather on Telegram. It will provide a token like: 123456789:ABC-defGHI...', max_length=200, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='1. Start a conversation with your bot on Telegram. 2. Visit https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates 3. Copy the "chat":{"id": ...} value.', max_length=100, verbose_name='Telegram Chat ID')),
                ('show_client_logos_section', models.BooleanField(default=True, help_text='Toggle whether the client logos strip appears on the homepage.', verbose_name='Show "Trusted By" Client Logos Section')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
