# Generated by Django 6.0.3 on 2026-09-03 09:33

from django.db import migrations, models

NEW_FIRM_NAME = 'Subhash Mishra & Associates'
OLD_FOOTER = (
    'Lex Chambers is a premier law firm committed to providing exceptional '
    'legal services with integrity and dedication.'
)
NEW_FOOTER = (
    'Subhash Mishra & Associates is a full-service litigation and advisory '
    'chambers committed to principled, strategic, and result-oriented '
    'representation across trial courts, High Courts, and the Supreme Court of India.'
)


def update_placeholder_siteconfig(apps, schema_editor):
    """Replace saved Lex Chambers placeholders on the live singleton row."""
    SiteConfig = apps.get_model('core', 'SiteConfig')
    for obj in SiteConfig.objects.all():
        changed = False
        if obj.firm_name == 'Lex Chambers':
            obj.firm_name = NEW_FIRM_NAME
            changed = True
        if obj.footer_about_text == OLD_FOOTER:
            obj.footer_about_text = NEW_FOOTER
            changed = True
        if changed:
            obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='firm_name',
            field=models.CharField(default='Subhash Mishra & Associates', max_length=200, verbose_name='Firm Name'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_about_text',
            field=models.TextField(blank=True, default='Subhash Mishra & Associates is a full-service litigation and advisory chambers committed to principled, strategic, and result-oriented representation across trial courts, High Courts, and the Supreme Court of India.', help_text='Short description shown in the footer beneath the logo.', verbose_name='Footer About Text'),
        ),
        migrations.RunPython(update_placeholder_siteconfig, noop_reverse),
    ]
