# Generated by Django 6.0.3 on 2026-09-03

from django.db import migrations

OLD = 'Lex Chambers'
NEW = 'Subhash Mishra & Associates'


def replace_placeholder_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    FlatPage = apps.get_model('flatpages', 'FlatPage')

    for obj in Site.objects.filter(name=OLD):
        obj.name = NEW
        obj.save()

    for obj in FlatPage.objects.all():
        content = obj.content or ''
        if OLD in content:
            obj.content = content.replace(OLD, NEW)
            obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_firm_name_defaults'),
        ('sites', '0002_alter_domain_unique'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_placeholder_name, noop_reverse),
    ]
