# Generated by Django 6.0.3 on 2026-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_replace_lex_chambers_site_flatpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='1. Start a conversation with your bot on Telegram. 2. Visit https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates 3. Copy the "chat":{"id": ...} value. To notify multiple people, separate their chat IDs with a comma (e.g. 123456789,987654321) — each person must message the bot at least once first.', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
