# Generated by Django 6.0.3 on 2026-09-05 11:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_siteconfig_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Displayed next to the firm name in the navbar. Recommended: square or circular, transparent background, at least 200×200px.', max_length=255, null=True, verbose_name='Firm Logo'),
        ),
    ]
