# Generated by Django 6.0.3 on 2026-09-02 13:56

import ckeditor_uploader.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, help_text='Recommended size: 1200×630px.', max_length=255, verbose_name='Featured Image')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Image Alt Text')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on list pages. If blank, auto-generated from body.', max_length=400, verbose_name='Excerpt')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full post content with rich text editor.', verbose_name='Post Body')),
                ('is_published', models.BooleanField(default=False, help_text='Only published posts are shown on the public site.', verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='Set this to schedule publication. Leave blank to publish immediately.', null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Category')),
                ('related_practice_area', models.ForeignKey(blank=True, help_text='Optional link to a practice area for cross-referencing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='practice_areas.practicearea', verbose_name='Related Practice Area')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
