# Generated by Django 6.0.3 on 2026-09-02 13:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('designation', models.CharField(help_text='e.g. "Senior Advocate", "Associate Attorney"', max_length=200, verbose_name='Designation / Title')),
                ('bio', models.TextField(help_text='Full professional biography.', verbose_name='Biography')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Professional headshot. Square format recommended (e.g. 400×400px).', max_length=255, verbose_name='Photo')),
                ('photo_alt', models.CharField(blank=True, help_text='Describe the photo for screen readers.', max_length=200, verbose_name='Photo Alt Text')),
                ('is_founder', models.BooleanField(default=False, help_text='The founder is featured prominently on the homepage and about page.', verbose_name='Is Founder')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
