# Generated by Django 6.0.3 on 2026-09-02 13:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='High-quality photograph. Recommended minimum 800×600px.', max_length=255, verbose_name='Image')),
                ('alt_text', models.CharField(help_text='Describe the image for screen readers. Required.', max_length=200, verbose_name='Alt Text')),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown in the lightbox.', max_length=300, verbose_name='Caption')),
                ('category', models.CharField(choices=[('justice', 'Justice & Law'), ('office', 'Our Office'), ('team', 'Our Team'), ('event', 'Events')], default='office', help_text='Used for the filter tabs on the gallery page.', max_length=20, verbose_name='Category')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
