# Generated by Django 6.0.3 on 2026-09-03

from django.db import migrations

OLD = 'Lex Chambers'
NEW = 'Subhash Mishra & Associates'


def replace_placeholder_captions(apps, schema_editor):
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    for obj in GalleryImage.objects.all():
        changed = False
        if OLD in (obj.caption or ''):
            obj.caption = obj.caption.replace(OLD, NEW)
            changed = True
        if OLD in (obj.alt_text or ''):
            obj.alt_text = obj.alt_text.replace(OLD, NEW)
            changed = True
        if changed:
            obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_placeholder_captions, noop_reverse),
    ]
