# Generated by Django 6.0.3 on 2026-09-02 13:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Client / Company Name')),
                ('logo', cloudinary.models.CloudinaryField(help_text='Company logo. PNG with transparent background preferred. Recommended: 200×80px.', max_length=255, verbose_name='Logo')),
                ('logo_alt', models.CharField(help_text='Describe the logo for screen readers (e.g. "Acme Corp logo").', max_length=200, verbose_name='Logo Alt Text')),
                ('url', models.URLField(blank=True, help_text='Optional link when the logo is clicked.', verbose_name='Company Website URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
