# Generated by Django 6.0.3 on 2026-09-02 13:56

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(blank=True, help_text='Paste a Heroicons/FontAwesome SVG code here (line-art style, will be gold-colored via CSS).', verbose_name='Icon SVG')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Auto-generated from title. Used in URLs.', max_length=220, unique=True, verbose_name='URL Slug')),
                ('short_description', models.TextField(help_text='2–3 sentences shown on the homepage card. Keep concise.', max_length=400, verbose_name='Short Description')),
                ('full_description', ckeditor.fields.RichTextField(help_text='Detailed description for the practice area detail page.', verbose_name='Full Description')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, help_text='Large image for the detail page header. Recommended 1400×600px.', max_length=255, verbose_name='Hero Image')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Hero Image Alt Text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive practice areas are hidden from the site.', verbose_name='Active')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag. Leave blank to use the practice area title.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description. Keep under 160 characters.', max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Practice Area',
                'verbose_name_plural': 'Practice Areas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
