# Generated by Django 6.0.3 on 2026-09-03

from django.db import migrations

OLD = 'Lex Chambers'
NEW = 'Subhash Mishra & Associates'


def replace_placeholder_copy(apps, schema_editor):
    PracticeArea = apps.get_model('practice_areas', 'PracticeArea')
    for obj in PracticeArea.objects.all():
        changed = False
        if OLD in (obj.meta_title or ''):
            replaced = obj.meta_title.replace(OLD, NEW)
            if len(replaced) <= 70:
                obj.meta_title = replaced
            else:
                # Firm name is longer than the old placeholder; drop the
                # suffix so effective_meta_title can append it dynamically.
                prefix = obj.meta_title.replace(f' | {OLD}', '').replace(OLD, '').strip()
                obj.meta_title = prefix[:70]
            changed = True
        if OLD in (obj.full_description or ''):
            obj.full_description = obj.full_description.replace(OLD, NEW)
            changed = True
        if OLD in (obj.short_description or ''):
            obj.short_description = obj.short_description.replace(OLD, NEW)
            changed = True
        if changed:
            obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('practice_areas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_placeholder_copy, noop_reverse),
    ]
